/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sbt_jni_samples_Overloads */

#ifndef _Included_com_github_sbt_jni_samples_Overloads
#define _Included_com_github_sbt_jni_samples_Overloads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sbt_jni_samples_Overloads
 * Method:    doSomething
 * Signature: (Lcom/github/sbt/jni/samples/A;)Lcom/github/sbt/jni/samples/B;
 */
JNIEXPORT jobject JNICALL Java_com_github_sbt_jni_samples_Overloads_doSomething__Lcom_github_sbt_jni_samples_A_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_sbt_jni_samples_Overloads
 * Method:    doSomething
 * Signature: (Lcom/github/sbt/jni/samples/B;)Lcom/github/sbt/jni/samples/A;
 */
JNIEXPORT jobject JNICALL Java_com_github_sbt_jni_samples_Overloads_doSomething__Lcom_github_sbt_jni_samples_B_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_github_sbt_jni_samples_Overloads
 * Method:    doSomething
 * Signature: ([Lcom/github/sbt/jni/samples/C;)Lcom/github/sbt/jni/samples/A;
 */
JNIEXPORT jobject JNICALL Java_com_github_sbt_jni_samples_Overloads_doSomething___3Lcom_github_sbt_jni_samples_C_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_github_sbt_jni_samples_Overloads
 * Method:    doSomething
 * Signature: (I[Lcom/github/sbt/jni/samples/C;Lcom/github/sbt/jni/samples/B;D)Lcom/github/sbt/jni/samples/A;
 */
JNIEXPORT jobject JNICALL Java_com_github_sbt_jni_samples_Overloads_doSomething__I_3Lcom_github_sbt_jni_samples_C_2Lcom_github_sbt_jni_samples_B_2D
  (JNIEnv *, jobject, jint, jobjectArray, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
