import scala.sys.process._

val scalaVersions = Seq("3.8.4", "2.13.18", "2.12.21", "2.11.12")
val macrosParadiseVersion = "2.1.1"

// Scala versions the plugin is cross-built with: 2.12 -> sbt 1.x, 3.x -> sbt 2.x
val sbt1PluginScala = "2.12.21"
val sbt2PluginScala = "3.8.4"

ThisBuild / versionScheme := Some("semver-spec")
ThisBuild / organization := "com.github.sbt"
ThisBuild / scalacOptions ++= Seq("-deprecation", "-feature")
ThisBuild / javacOptions ++= Seq("--release", "11")
ThisBuild / licenses := Seq(("BSD New", url("http://opensource.org/licenses/BSD-3-Clause")))
ThisBuild / homepage := Some(url("https://github.com/jodersky/sbt-jni"))
ThisBuild / developers := List(
  Developer(
    "jodersky",
    "Jakob Odersky",
    "jakob@odersky.com",
    url("https://jakob.odersky.com")
  ),
  Developer(
    "pomadchin",
    "Grigory Pomadchin",
    "@pomadchin",
    url("https://github.com/pomadchin")
  )
)

lazy val root = (project in file("."))
  .aggregate(core, plugin)
  .settings(
    publish := {},
    publishLocal := {},
    // make sbt-pgp happy
    publishTo := Some(Resolver.file("Unused transient repository", target.value / "unusedrepo")),
    // `test-plugin` runs scripted on the current axis (scriptedSbt follows pluginCrossBuild / sbtVersion);
    // the -sbt1 / -sbt2 variants pin the axis explicitly.
    addCommandAlias("test-plugin", ";+core/publishLocal;scripted"),
    addCommandAlias("test-plugin-sbt1", s";++$sbt1PluginScala;+core/publishLocal;scripted"),
    addCommandAlias("test-plugin-sbt2", s";++$sbt2PluginScala;+core/publishLocal;scripted")
  )

lazy val core = project
  .settings(
    name := "sbt-jni-core",
    scalaVersion := scalaVersions.head,
    crossScalaVersions := scalaVersions,
    scalacOptions += {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((3, _)) => "-Werror"
        case _            => "-Xfatal-warnings"
      }
    },
    scalacOptions ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, n)) if n <= 11 => Seq("-target:jvm-1.8")
        case Some((2, _))            => Seq("-release", "11")
        case _                       => Seq("-release", "17")
      }
    },
    libraryDependencies ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, n)) =>
          Seq(
            "org.scala-lang" % "scala-compiler" % scalaVersion.value % Provided,
            "org.scala-lang" % "scala-reflect" % scalaVersion.value
          )
        case _ => Seq("org.scala-lang" %% "scala3-compiler" % scalaVersion.value % Provided)
      }
    },
    libraryDependencies ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, n)) if n < 13 =>
          Seq(compilerPlugin(("org.scalamacros" % "paradise" % macrosParadiseVersion).cross(CrossVersion.full)))
        case _ => Seq()
      }
    },
    Compile / scalacOptions ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, n)) if n >= 13 => Seq("-Ymacro-annotations")
        case _                       => Seq()
      }
    }
  )

lazy val plugin = project
  .enablePlugins(SbtPlugin)
  .settings(
    name := "sbt-jni",
    scalaVersion := sbt1PluginScala,
    crossScalaVersions := Seq(sbt1PluginScala, sbt2PluginScala),
    // sbt 1.x plugins are built with Scala 2.12, sbt 2.x plugins with Scala 3
    pluginCrossBuild / sbtVersion := {
      scalaBinaryVersion.value match {
        case "2.12" => (pluginCrossBuild / sbtVersion).value
        case _      => "2.0.0-RC15"
      }
    },
    scalacOptions ++= {
      CrossVersion.partialVersion(scalaVersion.value) match {
        // `ProcessBuilder#lineStream` is deprecated on 2.13+ (use `lazyLines`), but `lazyLines`
        // does not exist on 2.12, so silence that single deprecation on the Scala 3 axis.
        case Some((3, _)) => Seq("-Werror", "-Wconf:msg=lineStream:s")
        case _            => Seq("-Xfatal-warnings")
      }
    },
    libraryDependencies ++= Seq("org.ow2.asm" % "asm" % "9.10.1", "org.scalatest" %% "scalatest" % "3.2.20" % Test),
    // make project settings available to source
    Compile / sourceGenerators += Def.task {
      val src = s"""|/* Generated by sbt */
                    |package com.github.sbt.jni
                    |
                    |private[jni] object ProjectVersion {
                    |  final val MacrosParadise = "${macrosParadiseVersion}"
                    |  final val Core = "${version.value}"
                    |}
                    |""".stripMargin
      val file = sourceManaged.value / "com" / "github" / "sbt" / "jni" / "ProjectVersion.scala"
      IO.write(file, src)
      Seq(file)
    }.taskValue,
    scriptedLaunchOpts := Seq(
      "-Dplugin.version=" + version.value,
      // boot each scripted test on the sbt version matching the current axis
      // (sbt 1.x on the 2.12 build, sbt 2.x on the Scala 3 build), so a single set
      // of example projects can be exercised against both sbt 1 and sbt 2.
      "-Dsbt.version=" + (pluginCrossBuild / sbtVersion).value,
      "-Xmx2g",
      "-Xss2m"
    )
  )
