/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_jodersky_jni_basic_Library__ */

#ifndef _Included_ch_jodersky_jni_basic_Library__
#define _Included_ch_jodersky_jni_basic_Library__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_jodersky_jni_basic_Library__
 * Method:    print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_jodersky_jni_basic_Library_00024_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
