#!/bin/bash
set -o errexit
set -o nounset
set -o verbose

sbt test-plugin

# Automatic publishing for tags that start with `v<digit>`
if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_TAG" =~ ^v[0-9].* ]]; then
    # Import gpg keys (download public key to check for renewal)
    gpg --keyserver keyserver.ubuntu.com --recv-keys "2B50AAFF11989ECC8531EB4A7C921C6769797655"
    openssl aes-256-cbc \
	    -K "$encrypted_35cdae908c05_key" \
	    -iv "$encrypted_35cdae908c05_iv" \
	    -in .travis/sec.gpg.enc \
	    -out sec.gpg -d
    gpg --import sec.gpg

    # Setup sbt-pgp plugin
    cat <<-EOF > project/gpg.sbt
	addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")
	EOF
    cat <<-EOF > gpg.sbt
	pgpSigningKey in Global := Some(0x7C921C6769797655l)
	useGpgAgent in Global := true
	useGpg in Global := true
	EOF

    # Setup bitray publishing plugin
    cat <<-EOF > project/bintray.sbt
	addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
	EOF
    mkdir ~/.bintray
    openssl aes-256-cbc \
	    -K "$encrypted_35cdae908c05_key" \
	    -iv "$encrypted_35cdae908c05_iv" \
	    -in .travis/bintray.enc \
	    -out ~/.bintray -d

    # Publish
    sbt +publishSigned
fi
