#!/bin/bash
set -o errexit
set -o nounset
set -o verbose

sbt test-plugin

# Automatic publishing for tags that start with `v<digit>`
if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_TAG" =~ ^v[0-9].* ]]; then
    # Import gpg keys (download public key to check for renewal)
    gpg --keyserver keyserver.ubuntu.com --recv-keys "2B50AAFF11989ECC8531EB4A7C921C6769797655"
    openssl aes-256-cbc \
	    -K "$encrypted_35cdae908c05_key" \
	    -iv "$encrypted_35cdae908c05_iv" \
	    -in .travis/sec.gpg.enc \
	    -out sec.gpg -d
    gpg --import sec.gpg

    # Setup sbt-pgp plugin
    cat <<-EOF > gpg.sbt
	credentials += Credentials(
	  "GnuPG Key ID",
	  "gpg",
	  "2B50AAFF11989ECC8531EB4A7C921C6769797655", // key identifier
	  "ignored" // this field is ignored; passwords are supplied by pinentry
	)
	EOF

    # Setup bintray publishing plugin
    mkdir ~/.bintray
    openssl aes-256-cbc \
	    -K "$encrypted_35cdae908c05_key" \
	    -iv "$encrypted_35cdae908c05_iv" \
	    -in .travis/bintray.enc \
	    -out ~/.bintray -d

    # Publish
    sbt +publish
fi
