/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_jni_demo_Library__ */

#ifndef _Included_org_example_jni_demo_Library__
#define _Included_org_example_jni_demo_Library__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_jni_demo_Library__
 * Method:    print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_jni_demo_Library_00024_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
